/**
 * Every word the interface says, in English.
 *
 * This file is the source; French and Japanese are GENERATED by
 * scripts/translate.mjs and typed against `Messages`, so a key added here and
 * forgotten there is a build error rather than a blank space on a page nobody
 * on this team can read. Never hand-edit a translation — the next run
 * overwrites it.
 *
 * What is NOT in here, on purpose:
 *  - recap and lesson content, which the model already writes in the
 *    student's language (lib/openai, students.instruction_language)
 *  - anything a teacher typed: student names, note titles, their branding
 *  - the twenty-seven teaching languages in lib/languages.ts, which are
 *    content labels rather than chrome
 *
 * Keys are grouped by where they appear, not by meaning, so that converting a
 * component means reading one block instead of searching the whole file.
 */
export const en = {
  /** Words that appear in more than one place. Keep this small. */
  common: {
    save: 'Save',
    saving: 'Saving…',
    saved: 'Saved',
    cancel: 'Cancel',
    close: 'Close',
    delete: 'Delete',
    edit: 'Edit',
    back: 'Back',
    next: 'Next',
    done: 'Done',
    loading: 'Loading…',
    retry: 'Try again',
    signOut: 'Sign out',
    somethingWrong: 'Something went wrong. Try again in a moment.',
  },

  /** components/AppNav.tsx — the teacher's rail and phone drawer. */
  nav: {
    appName: 'Lesson Studio',
    workspace: 'Teacher workspace',
    overviewAria: 'Lesson Studio overview',
    navAria: 'Teacher workspace navigation',
    openMenu: 'Open menu',
    closeMenu: 'Close menu',
    expand: 'Expand navigation',
    collapse: 'Collapse navigation',
    sectionWorkspace: 'Workspace',
    sectionManage: 'Manage',
    overview: 'Overview',
    students: 'Students',
    notes: 'Notes',
    materials: 'Materials',
    studentView: 'Student view',
    payments: 'Payments',
    availability: 'Availability',
    settings: 'Settings',
    /** Under the account name: what the calendar connection is actually doing. */
    calendarConnected: 'Calendar connected',
    setupNeeded: 'Setup needed',
    recordingsOnly: 'Recordings only',
    studentPortal: 'Student portal',
  },

  /** app/login and app/signup — the two pages nobody is signed in to. */
  auth: {
    language: 'Language',
    emailLabel: 'Email address',
    emailPlaceholder: 'you@example.com',
    passwordLabel: 'Password',

    signInTitle: 'Sign in',
    signInSub: 'Welcome back. Sign in to see your lessons, progress, and recaps.',
    signInExpired: 'Your session timed out. Sign in and we’ll take you straight back.',
    signInAction: 'Sign in',
    signingIn: 'Signing in…',
    passwordDots: '••••••••',
    forgotPassword: 'Forgot your password?',
    newHere: 'New here?',
    createAccountLink: 'Create a teacher account',
    freeToSetUp: 'Free to set up, and you can add your first student straight away.',
    studentQuestion: 'Are you a student?',
    studentAnswer:
      'Your teacher sends you an invite link — open it and you choose your own email and password. After that, you sign in right here.',
    signInHeadline: 'Every lesson, written up.',
    signInAside:
      'Lesson Studio turns each hour into a recap, a progress chart and a set of practice — for the teacher who ran it and the student who sat in it.',

    signUpTitle: 'Create a teacher account',
    signUpSub:
      'Start your Koku Library workspace for students, lesson recaps, bookings, and progress tracking.',
    fullNameLabel: 'Full name',
    passwordHint: 'At least 6 characters',
    createAccount: 'Create account',
    creatingAccount: 'Creating account…',
    createFailed: 'Could not create your account.',
    createdNowSignIn: 'Account created — please sign in.',
    haveAccount: 'Already have an account?',
    signUpHeadline: 'Your whole teaching practice, in one place.',
    signUpAside:
      'Set up in a couple of minutes. Add a student, record your next lesson, and the rest of this builds itself.',
  },

  /**
   * components/AuthAside.tsx — the carousel beside both auth forms.
   *
   * Order matters: the component pairs these with its artwork by INDEX, so
   * the translator is told not to reorder and the shape check enforces the
   * count. The labels inside the artwork itself ("SPEAKING BALANCE", the tab
   * names) are still English — they are a picture of the product rather than
   * the page's own copy, and translating a mock is a separate job.
   */
  aside: {
    slides: [
      {
        title: 'The lesson writes itself up',
        body: 'A Chrome extension records both voices. The recap comes back drafted — you edit and publish.',
      },
      {
        title: 'Progress they can actually see',
        body: 'Scores, talk-time and vocabulary tracked lesson to lesson, on a page built for the student.',
      },
      {
        title: 'Whatever language you teach',
        body: 'Japanese, French, Korean, Spanish and thirty-odd more — corrected in the language of the lesson, explained in the one your student thinks in.',
      },
      {
        title: 'Practice from their own words',
        body: 'Flashcards and speaking tests made from the vocabulary that came up in the hour.',
      },
      {
        title: 'A student portal with your name on it',
        body: 'Your colours, your wording, and only the sections you teach with.',
      },
    ],
  },

  /** components/OnboardingFlow.tsx — the five steps after a teacher signs up. */
  onboarding: {
    /** Order matters: the component indexes these by step number. */
    steps: ['Your lessons', 'Where you meet', 'Your calendar', 'Your student view', 'Your recorder'],
    sideTitle: 'Let’s set up your studio.',
    sideBody: 'Four quick steps and your students get a portal of their own.',
    stepCount: 'Step {n} of {total}',
    choose: 'choose…',
    continueAction: 'Continue',
    finish: 'Finish setup',
    finishing: 'Finishing…',

    couldNotSave: 'Could not save',
    couldNotFinish: 'Could not finish',
    pickTeaching: 'Pick the language you teach.',
    pickSpoken: 'Pick the language your lessons are spoken in.',
    pickCalendar: 'Tell us whether your lessons live on a calendar.',
    pickPortalName: 'Give the portal a name — your students will see it.',

    teachAria: 'The language you teach',
    iTeach: 'I teach',
    teachHint:
      'Recaps and practice tests are built for this language. It’s the default for every student you add — each student can be switched individually later.',
    spokenAria: 'The language your lessons are spoken in',
    spokenIn: 'my lessons are mostly spoken in',
    spokenHint:
      'Often not the language being learned — a beginner’s hour runs mostly in the language you share. It’s what the recorder listens for.',
    timezone: 'Your timezone',

    platformTitle: 'Where do you meet students?',
    platformLead:
      'On Meet or Zoom we create the link when a student books. On a marketplace the lesson already has a room, so we leave the link alone and take it from there.',
    zoomLater: 'Connect Zoom later in Settings',
    stayOutTitle: 'We’ll stay out of the lesson itself',
    stayOutBody:
      'No links created, no bot sent. You record the lesson yourself and the recap, vocabulary and practice are built from that — everything your students see works the same.',

    calendarTitle: 'Where do your lessons live?',
    /** {platform} is a marketplace name — Preply, italki — never translated. */
    calendarLeadExternal:
      'Some {platform} teachers still keep their week on Google Calendar, and some never leave the platform. Your answer decides what the workspace shows you.',
    calendarLead:
      'If your students are on your Google Calendar we can read the week, take bookings and send the recorder. If you schedule elsewhere, we stay out of it.',
    googleConnected: 'Google Calendar connected',
    googleConnectedSub: 'You can pick which calendar holds your lessons in Settings.',
    connectGoogle: 'Connect Google Calendar',
    connectGoogleFine:
      'You’ll be sent to Google’s consent screen and returned here. You can carry on without it, but bookings and automatic recording stay off until you connect.',
    recordTitle: 'Record the lesson',
    recordBody: 'Whatever room you teach in, capture it and hand the recording to Lesson Studio.',
    reviewTitle: 'Review the recap',
    reviewBody: 'It joins your review queue like any other lesson. Publish it and the student has it.',
    noCalendarFine:
      'No calendar, no booking page, no nagging — your workspace opens on lessons and recaps instead. Change your mind any time in Settings.',

    brandTitle: 'Make it yours',
    brandLead:
      'Pick a colour and a name for the portal your students sign in to. You can fine-tune everything later.',
    portalNameLabel: 'Student portal name',
    portalNamePlaceholder: 'e.g. Sakura Japanese',
    portalNameFine:
      'This is the name across the top of every student’s portal, and on the invite they open. Your own studio name, not ours.',
    accent: 'Accent colour',
    previewTagline: 'Learn today, succeed tomorrow!',

    recorderTitle: 'Install the recorder',
    recorderLead:
      'This is the part that does the work: a Chrome extension that records your lesson and writes the recap. No bot joins the call, and nothing is installed on your student’s side.',
    recorderStep1Bold: 'Add it from the Chrome Web Store',
    recorderStep1: ' — one click, then pin it to your toolbar.',
    recorderStep2Bold: 'Sign in inside the extension',
    recorderStep2: ' with this same email and password. There is nothing to copy across.',
    recorderStep3Bold: 'Record a lesson',
    recorderStep3: ': pick the student, hit start, hit stop at the end.',
    addToChrome: 'Add to Chrome — it’s free ↗',
    recorderFinePre: 'Prefer the full walkthrough (mic permission, what gets recorded)? It’s on the ',
    recorderFineLink: 'setup guide',
    recorderFineMid: ' — also at ',
    recorderFineBold: 'Settings → Lesson recorder',
    recorderFinePost: ' whenever you’re ready.',
  },
  /** app/page.tsx — the Overview page and the Google connect wall. */
  overview: {
    eyebrow: 'Overview',
    title: 'Your teaching calendar',
    manageConnections: 'Manage connections',
    fixInSettings: 'Fix it in Settings',
    summaryAria: 'Lesson summary',
    upcoming: 'Upcoming lessons',
    drafts: 'Drafts to review',
    draftsSub: 'recaps waiting on you',
    published: 'Published recaps',
    publishedSub: 'sent to students',
    writeUpsLeft: 'Write-ups left',
    writeUpsAria: 'Write-ups left — buy more',
    /** {used} of {total} free, while they are still on the trial balance. */
    usageTrial: '{used} used of your {total} free',
    usageBought: '{used} built · they don’t expire',
    lessonCalendar: 'Lesson calendar',
    primaryCalendar: '(primary)',
  },

  /** app/page.tsx — shown when Google Calendar is not connected yet. */
  connect: {
    title: 'Connect your Google Calendar',
    body:
      'Link your calendar so Lesson Studio can see your upcoming lessons, take bookings, and record each class.',
    notConfiguredPre: 'Google OAuth isn’t configured yet. Add ',
    notConfiguredMid: ' and ',
    notConfiguredPost: ' to the environment, then restart.',
    scopeReadBold: 'Read your calendar',
    scopeRead: ' — find lessons and their meeting links',
    scopeRecordBold: 'Record lessons',
    scopeRecord: ' — capture classes with the Lesson Studio extension',
    scopeRecapBold: 'Build recaps',
    scopeRecap: ' — AI lesson summaries for you to review and share',
    continueGoogle: 'Continue with Google',
    fine: 'You’ll be sent to Google’s consent screen. Manage this later in Settings.',
  },
  /** app/settings/page.tsx */
  settings: {
    eyebrow: 'Workspace',
    title: 'Settings',

    recorderTitle: 'Lesson recorder',
    recorderDesc: 'The Chrome extension that records a lesson and turns it into a recap. ',
    recorderGuide: 'Step-by-step guide →',
    replayTourHint: 'Forgot what a page is for? The walkthrough runs again from here.',

    languageTitle: 'Language',
    languageDesc:
      'What this workspace says to you. It does not change the language your recaps are written in — each student chooses that for themselves.',

    connectionsTitle: 'Connections',
    connectionsDesc: 'Connect the tools that power scheduling, meetings, and payments.',

    livesTitle: 'Where your lessons live',
    livesDesc:
      'Keep them on Google Calendar and you get a booking page, free-slot scheduling and automatic recording. Schedule elsewhere and the workspace drops all of that and works from recordings.',

    calendarTitle: 'Lesson calendar',
    calendarDesc: 'Which of your calendars holds the lessons Lesson Studio should read?',
    primaryCalendar: 'Primary calendar',

    speakingTitle: 'Speaking exercises',
    speakingDesc:
      'Every recap ends with three speaking exercises. Let your students record their answers and the takes land on the lesson page, under the sentence they were answering — and you get an email when they do. Turn it off and those three exercises come off the recap entirely.',
    speakingOn: 'Let students record them',
    speakingOnHint: 'You listen back on the lesson page',
    speakingOff: 'Leave them out',
    speakingOffHint: 'The recap keeps its seven written exercises',

    platformTitle: 'Default meeting platform',
    platformDesc:
      'What a new booking creates. Pick the last one if your lessons live on a marketplace and the link is already theirs.',
    meetLabel: 'Google Meet',
    meetHint: 'Created on your calendar',
    ownLinkLabel: 'I share my own link',
    ownLinkHint: 'Preply, italki, or a room of your own',
  },
  /** components/SubscriptionPanel.tsx — Settings → Lessons. */
  billing: {
    leftTitle: 'Write-ups left',
    leftDesc: 'One is spent each time a lesson is written up. They do not expire and nothing renews.',
    /** {total} free, and {used} of them gone. */
    ofFree: 'of your {total} free write-ups',
    usedSuffix: ' · {used} used',
    builtSoFar: '{used} built so far',
    emptyTrial:
      'That is the free ones used. A pack below keeps your lessons being written up — there is no subscription and no renewal date.',
    emptyPaid:
      'Your balance is empty. A pack below tops it back up, and whatever you do not use stays there.',

    addTitle: 'Add write-ups',
    addDesc:
      'One payment, no renewal. Bigger packs cost less — but the small one is not a penalty, and whatever you buy is yours until you use it.',
    lessonsWrittenUp: 'lessons written up',
    save: 'save {pct}%',
    neverExpires: 'Never expires',
    buy: 'Buy {n}',
    paidOnce: 'Paid once, by card, through Stripe. No card is kept here and nothing charges you again.',
    /**
     * Pack tags, indexed to PACKS in lib/plans.ts. They live here rather than
     * in plans.ts because that module is imported by the Stripe script and by
     * API routes, where a dictionary lookup makes no sense — and because a
     * module constant is evaluated once at import, so a tag baked in there
     * would survive every language change on the page.
     */
    packTags: ['Starting out', 'A steady schedule', 'Most popular'],
  },
  /** components/RecapReviewPage.tsx — the draft a teacher checks before sending. */
  recap: {
    /**
     * DISPLAY labels, indexed to the component's TABS ids. The second reads
     * "Recap" while its id is 'Lesson' — that mapping used to be a label()
     * helper in the component, which would have needed a translation path of
     * its own.
     */
    tabs: ['Progress', 'Recap', 'Homework', 'Vocabulary'],
    tabsAria: 'Recap sections',
    eyebrow: 'Review before sending',
    /** {name} is the student's own name and is never translated. */
    title: '{name} · Lesson recap',
    lessonFallback: 'Lesson',
    /** {first} is the student's first name. */
    sub: 'review each tab, then send it to {first}.',

    translate: 'Translate explanations',
    translateTitle:
      'Rewrite the explanations in the student’s language — lesson material and scores stay untouched',
    working: 'Working…',
    rebuild: 'Rebuild from recording',
    rebuildTitle: 'Regenerate from the recording with the latest AI + metrics',
    rebuilding: 'Rebuilding…',

    deleteDraft: 'Delete draft',
    deleting: 'Deleting…',
    saveDraft: 'Save draft',
    approve: 'Approve & send',
    sending: 'Sending…',
    savedTick: 'Saved ✓',

    confirmRebuild:
      'Rebuild this recap from the recording? This regenerates the summary, sections, homework and fluency metrics, and discards any manual edits.',
    confirmTranslate:
      'Translate the explanations in this recap into the language this student is taught through? Example sentences, quotes and scores stay as they are.',
    /** {name} is the student's own name. */
    confirmDelete:
      'Delete {name}’s draft recap? This removes it from Recaps to review and cannot be undone.',
    promptLanguage:
      'This student has no explanation language set yet (you can set one on their student page). Translate the explanations into which language?',

    rebuildFailed: 'Rebuild failed',
    translationFailed: 'Translation failed',
    deleteFailed: 'Could not delete recap',
    savingEdits: 'Saving your edits…',
    uploadingMemo: 'Uploading your voice memo…',
    /** {name} is the file's own name. */
    uploadingFile: 'Uploading {name}…',
    attachingMaterials: 'Attaching your materials…',
    attachmentFailed:
      'Recap sent, but an attachment failed to upload — add it from the lesson page.',
    suggestedScript: 'Suggested script',
  },
  /**
   * The student portal.
   *
   * `slots` are the DEFAULTS for lib/brand.ts TEXT_SLOTS — the headings a
   * teacher can rename in the Branding Studio. Translating them here is
   * correct precisely because they are defaults: resolveLabels overlays
   * whatever the teacher actually typed on top, so their own wording is
   * never machine-translated, and a heading they left alone follows the
   * student instead of being stuck in English. Keys must match TEXT_SLOTS
   * exactly or the overlay silently misses.
   */
  portal: {
    slots: {
      greeting: 'Welcome back,',
      tabOverview: 'Overview',
      tabLessons: 'Lessons',
      tabProgress: 'Progress',
      tabPractice: 'Practice',
      tabFiles: 'Files',
      tabTests: 'Tests',
      statLessons: 'Lessons',
      statScore: 'Avg score',
      statSpeaking: 'Speaking',
      lessonsTitle: 'Your lessons',
      progressTitle: 'Your progress',
      vocabTitle: 'Vocabulary',
      milestoneTitle: 'Next milestone',
      scoresTitle: 'Recent scores',
      testsTitle: 'Practice tests',
      speakingTitle: 'Speaking habits',
      filesTitle: 'Lesson files',
      vocabTotalsTitle: 'Vocabulary growth',
    },

    tabsAria: 'Dashboard sections',
    notLinked: 'Account not linked yet',
    askTeacher: 'Ask your teacher to link your account.',

    /** The speaking arc. {delta}, {now} and {then} are percentages. */
    climbLed: 'You went from listening to',
    climbLedEm: 'leading the conversation',
    climbMorePre: 'You are speaking',
    climbMoreEm: '{delta} points more',
    climbMorePost: 'than when you started.',
    climbPlainPre: 'You spoke',
    climbPlainPost: 'of your last lesson.',
    youSpoke: 'You spoke',
    acrossLessons: 'Across {n} lessons',
    acrossOneLesson: 'Across 1 lesson',
    climbSubPre: 'The mark on the arc is where you started —',
    climbDelta: '{delta} points since lesson 1',

    inLast30: '{n} in the last 30 days',
    totalLessons: 'Total lessons completed',
    inAll: '{n} in all',
    words: '{n} words',
    lastN: 'Last {n}',

    metricPace: 'Pace',
    metricThinking: 'Thinking time',
    metricShare: 'Your share',

    practiseTitle: 'Practise your words',
    practiceHistory: 'Practice, last two weeks',
    byKind: 'By kind of word',
    byLesson: 'By lesson',
    practiseAnything: 'Practise anything',
    practiseDue: 'Practise what is due',
    vocabKnown: 'known',
    vocabLearning: 'learning',
    vocabNew: 'not started',
    download: 'Download',
  },
  /** components/portal/PracticeDeck.tsx — flashcards, in the student's hands. */
  practice: {
    emptyTitle: 'Nothing to practise yet',
    emptyBody: 'Words appear here once your teacher publishes a lesson recap.',
    howMany: 'How many today?',
    /** {n} cards finished this round. */
    doneTitle: 'Done — {n} cards.',
    doneOneTitle: 'Done — 1 card.',
    allFirstTime: 'Every one first time. They will come back in a few days.',
    /** {right} first time, {missed} to see again sooner. */
    someMissed: '{right} first time, {missed} to see again sooner.',
    /** {n} words still in the pile. */
    moreLeft: '{n} more words in this pile, whenever you like.',
    oneLeft: '1 more word in this pile, whenever you like.',
    wholePile: 'That is the whole pile.',
    nextRound: '{n} more',
    practiseAgain: 'Practise again',
    backToPractice: 'Back to practice',
    tapToSee: 'Tap to see the meaning',
    again: 'Again',
    knewIt: 'Knew it',
    sayOutLoud: 'Say it out loud before you flip it.',
  },

  /** components/portal/RecapRating.tsx — the one question under every recap. */
  rating: {
    question: 'Did this match your lesson?',
    yes: 'Yes, that was my lesson',
    no: 'Not quite',
    thanksYes: 'You said this one matched your lesson. Thank you — it is read.',
    thanksNo: 'You said this one was off. Thank you — that is the useful kind.',
    whatWasOff: 'What was off? Pick any that fit.',
    notePlaceholder: 'If you can, say which part — a sentence is plenty.',
    send: 'Send',
    sending: 'Sending…',
    didNotSave: 'That did not save.',
    /**
     * Indexed to RATING_REASONS in lib/ratings.ts. The KEYS stay there — they
     * are written to the database and must never move with a translation.
     */
    reasons: [
      'Words I never said',
      'Mixed up who said what',
      'Wrong script or language',
      'Too easy or too hard for me',
      'Something else',
    ],
  },

  /** components/portal/RecapLanguagePicker.tsx */
  recapLanguage: {
    question: 'My recaps are written in',
    hint: 'The language you are learning stays as it is — this is the language everything around it is explained in.',
    aria: 'The language my recaps are explained in',
    saved: 'Saved — from your next recap on.',
    didNotSave: 'That did not save.',
  },
  /** components/LessonPageTabs.tsx — the page a published recap lands on. */
  lesson: {
    railAria: 'Lesson sections',
    thisLesson: 'This lesson',
    /**
     * Indexed to LESSON_MOVEMENTS in lib/brand.ts. The ids stay there — they
     * are stored in a teacher's saved layout, so they must never move with a
     * translation.
     */
    movements: [
      'How you spoke',
      'What you nailed',
      'What to fix',
      'What we covered',
      'Words from today',
      'Practice',
      'Files & audio',
    ],
    speakingBalance: 'Speaking balance',
    score: 'Score',
    grammarDensity: 'Grammar density',
    corrections: 'Corrections',
    homework: 'Homework',
    noHomework: 'No homework for this lesson.',
    practiceExercises: 'Practice exercises',
    wordsFromLesson: 'Words from this lesson',
    whoTalked: 'Who did the talking',
    speakingMeasured: 'Your speaking, measured',
    yourTeacher: 'Your teacher',
  },
  /** components/portal/JoinCard.tsx — the invite link a student opens. */
  join: {
    setupFailed: 'Could not set up your account.',
    acceptFailed: 'Could not accept the invite.',
    joining: 'Joining…',
    /** {name} is the email they are already signed in as. */
    joinAs: 'Join as {name}',
    notYouPre: 'Not you? ',
    notYouLink: 'Sign out',
    notYouPost: ' and open this link again.',
    emailLabel: 'Your email address',
    passwordLabel: 'Choose a password',
    passwordHint: 'At least 8 characters',
    settingUp: 'Setting up…',
    createAccount: 'Create my account',
  },

  /** components/portal/SpeakingRecorder.tsx — the student answering out loud. */
  speaking: {
    cta: 'Record your answer',
    sendFailed: 'Could not send that recording. Try again.',
    recordAgain: 'Record it again',
    sendToTeacher: 'Send to teacher',
    sending: 'Sending…',
    tryAgain: 'Try again',
    keepSent: 'Keep the one I sent',
  },

  /** components/portal/LessonExchange.tsx — files and audio on a lesson. */
  exchange: {
    recording: 'Recording',
    download: 'Download',
    nothingShared: 'Nothing shared for this lesson yet.',
    noFiles: 'No files shared yet. Upload a presentation or PDF for this lesson.',
    audioIntro:
      'Free practice this student recorded for the lesson. Their answers to the speaking exercises are on the Practice tab.',
    noAudio: 'No audio submitted yet.',
  },

  /**
   * components/portal/ProgressCharts.tsx — the swipeable metrics.
   * Indexed to METRICS; the `key` values stay in the component because they
   * name fields on the data.
   */
  charts: {
    metrics: [
      { label: 'Score', note: 'What each lesson was marked out of ten.' },
      { label: 'You talk', note: 'Your share of the talking. More of it is yours as you get more confident.' },
      { label: 'Pace', note: 'Words a minute while you were speaking.' },
      { label: 'Thinking', note: 'How long before you answer. Shorter means the words are coming faster.' },
      { label: 'Vocabulary', note: 'Every word from every lesson, added up.' },
    ],
    nothingYet: 'Nothing recorded for this yet.',
    /** {n} is the lesson number the comparison starts from. */
    sinceLesson: 'since lesson {n}',
    trendLater: 'The trend appears after your next lesson.',
  },

  /** components/TestView.tsx and app/student/practice */
  tests: {
    saveScoreFailed: 'Could not save your score.',
    /** {pct} is the score as a whole percent. */
    finish: 'Finish — {pct}%',
    allWords: 'All your words',
  },
  /** components/AvailabilityEditor.tsx — Settings → Availability. */
  availability: {
    /** Indexed to the component's DAYS array, which carries the weekday numbers. */
    days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    startTime: 'Start time',
    endTime: 'End time',
    removeRange: 'Remove range',
    couldNotSave: 'Could not save',
    saveChanges: 'Save changes',
    defaultsTitle: 'Lesson defaults',
    defaultsDesc: 'How long lessons are and how far ahead students can book you.',
    lessonName: 'Lesson name',
    lessonNamePlaceholder: 'Language lesson',
    lessonLength: 'Lesson length (min)',
    slotInterval: 'Slot interval (min)',
    minNotice: 'Min notice (hours)',
    bufferBefore: 'Buffer before (min)',
    bufferAfter: 'Buffer after (min)',
    maxPerDay: 'Max lessons / day',
    bookingWindow: 'Booking window (days)',
    title: 'Availability',
    copyMon: 'Copy Mon → weekdays',
    copyMonTitle: 'Copy Monday’s hours to Tue–Fri',
    previewBooking: 'Preview booking page ↗',
    unavailable: 'Unavailable',
    dateOverrides: 'Date overrides',
  },

  /** components/RecordingsOverview.tsx — the home page for a teacher with no calendar. */
  recordings: {
    eyebrow: 'Overview',
    title: 'Lessons & recaps',
    settings: 'Settings',
    yourStudents: 'Your students',
    publishedTitle: 'Published lessons',
    publishedDesc:
      'What your students can already see, newest first. Drafts wait in the review queue above.',
    nothingPublished: 'Nothing published yet',
    untitled: 'Untitled lesson',
    published: 'Published',
    draft: 'Draft',
    summaryAria: 'Lesson summary',
    students: 'Students',
    changedMind: 'Changed your mind?',
    connectCalendar: 'Connect a calendar',
  },

  /** components/LessonRow.tsx — one lesson in the calendar, and its recap modal. */
  lessonRow: {
    joinCall: 'Join call ↗',
    viewRecap: 'View recap',
    reviewRecap: 'Review recap',
    noLink: 'No link',
    eyebrow: 'Review before publishing',
    /** {title} is the lesson's own title. */
    recapTitle: '{title} · Lesson recap',
    closeAria: 'Close recap review',
    draftBanner: 'AI draft — review the content below before it reaches the student.',
    score: 'Score',
    studentTalk: 'Student talk',
    grammar: 'Grammar',
    confidence: 'Confidence',
    homework: 'Homework',
    memoScript: 'Voice memo script',
    teacherNote: 'Teacher’s note',
    editLater: 'Edit later',
    approveSend: 'Approve & send to student',
  },
  /** app/book/page.tsx — the public booking page a student is sent a link to. */
  book: {
    months: ['January', 'February', 'March', 'April', 'May', 'June',
             'July', 'August', 'September', 'October', 'November', 'December'],
    loadFailed: 'Could not load availability.',
    bookingFailed: 'Booking failed.',
    bookingFailedRetry: 'Booking failed — try again.',
    eyebrow: 'Schedule a lesson',
    title: 'Find a time that works',
    sub: 'Pick a day, then choose a time. Your confirmation and meeting details arrive by email.',
    booked: 'You’re booked!',
    invitePre: 'A calendar invite is on its way to',
    openMeeting: 'Open meeting link',
    noCalendar: 'Availability unavailable. Is the calendar connected?',
    noTimes: 'No open lesson times in the next 30 days.',
    pickDay: 'Pick a day',
    pickDayHint: 'Days with a dot have open times.',
    yourDetails: 'Your details',
    /** {time} is already formatted for the reader's locale. */
    confirmAt: 'Confirm {time}',
    yourName: 'Your name',
    namePlaceholder: 'Jane Doe',
    yourEmail: 'Your email',
    emailPlaceholder: 'you@email.com',
    booking: 'Booking…',
    bookAt: 'Book lesson · {time}',
  },

  /** components/GuidedTour.tsx — the first-run walkthrough. */
  tour: {
    /** Indexed to the component's STEPS; the `tour` anchors stay in the code. */
    steps: [
      { title: 'Overview', body: 'Home base. Recaps land here for you to review, and your latest lessons stack up below them.' },
      { title: 'Students', body: 'Add each student here. Their lessons, tests and progress all hang off this list — and each gets a portal of their own.' },
      { title: 'Notes', body: 'One click per lesson taught: a month grid that doubles as your teaching diary.' },
      { title: 'Student view', body: 'Exactly what your students see, restyled to your taste — colours, names, sections. Not a mock-up: the real thing.' },
      { title: 'Payments', body: 'Log what each student paid and how many lessons it covers. The balance counts down as recaps publish.' },
      { title: 'Settings', body: 'Your calendar, the lesson recorder, and your account. This tour lives here too, if you ever want it again.' },
    ],
    skip: 'Skip tour',
  },
} as const

/**
 * Deliberately NOT widened here — see the type below.
 *
 * `as const` above makes every English string its own literal type, which
 * would then demand the German file also say "Save". `Messages` widens them
 * back to string, keeping the SHAPE enforced (every key, every nesting level)
 * which is the part that catches a missing translation.
 */
type Widen<T> = T extends string
  ? string
  : T extends readonly (infer E)[]
    // readonly, not a mutable array: the generated files are `as const` too,
    // and a readonly tuple is not assignable to a mutable array. Keeping the
    // modifier means both sides agree and nothing here is ever mutated.
    ? readonly Widen<E>[]
    : { -readonly [K in keyof T]: Widen<T[K]> }

export type Messages = Widen<typeof en>
