/**
 * Every word the interface says, in English.
 *
 * This file is the source; French and Japanese are GENERATED by
 * scripts/translate.mjs and typed against `Messages`, so a key added here and
 * forgotten there is a build error rather than a blank space on a page nobody
 * on this team can read. Never hand-edit a translation — the next run
 * overwrites it.
 *
 * What is NOT in here, on purpose:
 *  - recap and lesson content, which the model already writes in the
 *    student's language (lib/openai, students.instruction_language)
 *  - anything a teacher typed: student names, note titles, their branding
 *  - the twenty-seven teaching languages in lib/languages.ts, which are
 *    content labels rather than chrome
 *
 * Keys are grouped by where they appear, not by meaning, so that converting a
 * component means reading one block instead of searching the whole file.
 */
export const en = {
  /** Words that appear in more than one place. Keep this small. */
  common: {
    save: 'Save',
    saving: 'Saving…',
    saved: 'Saved',
    cancel: 'Cancel',
    close: 'Close',
    delete: 'Delete',
    edit: 'Edit',
    back: 'Back',
    next: 'Next',
    done: 'Done',
    loading: 'Loading…',
    retry: 'Try again',
    signOut: 'Sign out',
    somethingWrong: 'Something went wrong. Try again in a moment.',
  },

  /** components/AppNav.tsx — the teacher's rail and phone drawer. */
  nav: {
    appName: 'Lesson Studio',
    workspace: 'Teacher workspace',
    overviewAria: 'Lesson Studio overview',
    navAria: 'Teacher workspace navigation',
    openMenu: 'Open menu',
    closeMenu: 'Close menu',
    expand: 'Expand navigation',
    collapse: 'Collapse navigation',
    sectionWorkspace: 'Workspace',
    sectionManage: 'Manage',
    overview: 'Overview',
    students: 'Students',
    notes: 'Notes',
    materials: 'Materials',
    studentView: 'Student view',
    payments: 'Payments',
    availability: 'Availability',
    settings: 'Settings',
    /** Under the account name: what the calendar connection is actually doing. */
    calendarConnected: 'Calendar connected',
    setupNeeded: 'Setup needed',
    recordingsOnly: 'Recordings only',
    studentPortal: 'Student portal',
  },
} as const

/**
 * Deliberately NOT widened here — see the type below.
 *
 * `as const` above makes every English string its own literal type, which
 * would then demand the German file also say "Save". `Messages` widens them
 * back to string, keeping the SHAPE enforced (every key, every nesting level)
 * which is the part that catches a missing translation.
 */
type Widen<T> = T extends string
  ? string
  : T extends readonly (infer E)[]
    ? Widen<E>[]
    : { -readonly [K in keyof T]: Widen<T[K]> }

export type Messages = Widen<typeof en>
